version: '3.9'

networks:
  demonetwork:

services:
  demoappdb:
    container_name: app-db
    image: "mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04"
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - demonetwork
  lightcleanarchitecturewebapi:
    container_name: lca-app
    image: ${DOCKER_REGISTRY-}lightcleanarchitecturewebapi
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - 8081:8081
      - 8080:8080
    depends_on:
      - demoappdb
    environment:
      - DB_HOST=demoappdb
      - DB_NAME=DemoBlazorApp
      - DB_SA_PASSWORD=password@12345#
    networks:
      - demonetwork
